# Generated by Django 4.0.2 on 2022-03-17 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treecher', '0005_remove_teacher_id_alter_teacher_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('Students', models.ManyToManyField(related_name='Students', to='treecher.Student')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='treecher.teacher')),
            ],
        ),
    ]
