# Generated by Django 4.0.2 on 2022-03-24 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(default='irnbea', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 15, 40, 15, 627216, tzinfo=utc)),
        ),
    ]
