# Generated by Django 4.0.2 on 2022-03-22 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treecher', '0005_remove_teacher_id_alter_teacher_user_and_more'),
        ('classroom', '0002_alter_classroom_students_alter_classroom_join_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='Students',
            field=models.ManyToManyField(blank=True, related_name='Students', to='treecher.Student'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(default='vnhxge', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 16, 27, 3, 431676)),
        ),
    ]
