# Generated by Django 4.0.2 on 2022-03-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_teacher_alter_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
