# Generated by Django 4.0.2 on 2022-03-24 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_join_code_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(default='zhlkyl', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 16, 43, 36, 453808, tzinfo=utc)),
        ),
    ]
