# Generated by Django 4.0.2 on 2022-03-18 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treecher', '0005_remove_teacher_id_alter_teacher_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0003_classroom_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='treecher.teacher'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(default='xnmuxo', max_length=7),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_posts', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
