# Generated by Django 4.0.2 on 2022-03-22 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_remove_question_classroom_alter_classroom_join_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(default='ssxoin', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 0, 13, 12, 354104)),
        ),
    ]
