# Generated by Django 4.0.2 on 2022-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_remove_post_title_alter_classroom_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(default='clkrcz', max_length=7),
        ),
    ]
