# Generated by Django 4.0.2 on 2022-03-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treecher', '0002_classroom_students_newuser_is_student_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
