# Generated by Django 4.0.2 on 2022-03-17 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treecher', '0003_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='Students',
            field=models.ManyToManyField(related_name='Students', to='treecher.Student'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
    ]
